### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by rimmesbe** [xnstt/prj-rev-bwfs-dasmoto#1]
Try to keep your code indented correctly. All these divs should be indented from the body tag, and all siblings should be at the same level. This will be more important when projects grow in size.

https://github.com/xnstt/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L9-L27

**Comment by xnstt** [comment]
Noted. So the siblings should also be indented inside the divs?
