### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [xnstt/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Good job on this project, it looks accurate to the spec. Your code is well organized and well thought out. I like that you made sections with divs and put id's on the divs. The price attribute on the spans was correct just needs to be a class instead of id. The biggest thing to work on moving forward is being DRY (Don't Repeat Yourself). In css your going to rely heavily on classes to do this, as well as other relational selectors. https://adam-marsden.co.uk/css-cheat-sheet/

**Comment by xnstt** [comment]
thank you for your review
